gcc-7-release:
  tags:
    - artful
  script:
    - git submodule update --init --recursive
    - export CXX=g++-7
    - export CC=gcc-7
    - mkdir -p build-gcc-7-release
    - cd build-gcc-7-release
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j12 tar-test
    - ./tar-test

clang-5-debug-asan:
  tags:
    - artful
  script:
    - git submodule update --init --recursive
    - export CXX=clang++
    - export CC=clang
    - export CXXFLAGS="-stdlib=libc++ -fsanitize=address -fno-omit-frame-pointer"
    - mkdir -p build-clang-5-debug-asan
    - cd build-clang-5-debug-asan
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j12 tar-test
    - ./tar-test

gcc-7-valgrind:
  tags:
    - artful
  script:
    - git submodule update --init --recursive
    - export CXX=g++-7
    - export CC=gcc-7
    - mkdir -p gcc-7-valgrind
    - cd gcc-7-valgrind
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j12 tar-test
    - valgrind --leak-check=full --show-reachable=yes ./tar-test

msvc-release:
  tags:
    - windows
  script:
    - git submodule update --init --recursive
    - set WD=%cd%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - cd %WD%
    - mkdir build-msvc-release
    - cd build-msvc-release
    - cmake -G "NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=Release ..
    - jom tar-test
    - tar-test

msvc-debug:
  tags:
    - windows
  script:
    - git submodule update --init --recursive
    - set WD=%cd%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - cd %WD%
    - mkdir build-msvc-debug
    - cd build-msvc-debug
    - cmake -G "NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=Debug ..
    - jom tar-test
    - tar-test

clang-format:
  tags:
    - artful
  script:
    - git submodule update --init --recursive
    - mkdir build-clang-format
    - cd build-clang-format
    - cmake ..
    - make tar-format-check

clang-tidy:
  tags:
    - artful
  script:
    - git submodule update --init --recursive
    - export CXX=clang++
    - export CC=clang
    - export CXXFLAGS="-stdlib=libc++"
    - mkdir build-clang-tidy
    - cd build-clang-tidy
    - cmake ..
    - make -j12 tar-lint